services:
  bot:
    build: .
    container_name: bot
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    restart: always