# syntax=docker/dockerfile:1

FROM python:3.10

WORKDIR /usr/src/app

COPY . .

RUN . venv/bin/activate
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install nodejs -y

CMD [ "python", "-m", "app.main" ]
